### ISSUE TITLE
Poor documentation and vital missing parts.

### ISSUE THREAD

**Issue by tretron** [willem-pennings/ClockSquared#1]
The documentation of this project is poor, I had to rework most of the dementions to make it work. however the worst part is the code, nothing gets explained. using the serial monitor resets the time...sometimes. and it is not clear how to select the date. I have added the following:

//setTime(1516265031); // set system time however uncomment after time is set

in order to temporarily set the time to EPOCH time. and after that manually adjust the time. Please adjust the code so it's easier to read and profide some documentation on how to adjust the time to current date via epoch time. or allow the serial monitor to set a EPOCH time.

**Comment by willem-pennings** [comment]
- I do not understand what you mean by 'reworking dementions'.

- This sketch does not include any code to set the time of a RTC by purpose, since there is no easy way of configuring time using the button interface. This should be done using a separate DS3231-compatible sketch and only needs to be done again once the RTC battery runs out (this takes several years). Many sketches to configure time on a DS3231 RTC are available online.

- You mention that 'nothing gets explained'. The code is filled with comments which should help you understand it. If there still are parts that you do not understand after careful evaluation, please let me know such that I can provide some additional comments. It should also be noted that all of the `displayTime ` function is based on Dutch language - the words used to indicate 13:20 are very different in Dutch than in English. This might be hard to comprehend for someone who does not speak the language.
